### ISSUE TITLE
TeamCity Service Messages don't work when issued from the Bazel build run with this plugin

### ISSUE THREAD

**Issue by konste** [JetBrains/teamcity-bazel-plugin#14]
We try to send some Service Messages, such as `##teamcity[message text='test message']` from the build and cannot make it to work - we see them in the build log, but they are not interpreted by TeamCity.

We know that Bazel sends most of the build output to stderr and Service Messages supposed to be sent through stdout, so we made Bazel build to run a Python script that sends the Service Messages we need to stdout. 

Why it does not work and what can we do to work around it?

For the test we tried to send the same messages from another (not Bazel) build step and they work as expected.

**Comment by NikolayPianikov** [comment]
@konste please try [this plugin](https://teamcity.jetbrains.com/repository/download/TeamCityPluginsByJetBrains_TeamcityBazelPlugin_Build/3131254:id/teamcity-bazel-plugin.zip)

**Comment by konste** [comment]
Our IT hesitates to install TC plugin which is not listed on this page: https://plugins.jetbrains.com/plugin/11248-bazel-build-support/versions
If you are pretty sure it fixes the problem, could you please publish it there?

**Comment by konste** [comment]
After all I persuade them to install it and can confirm the issue is fixed! Please publish it now.

**Comment by NikolayPianikov** [comment]
@konste thanks, I just wanted to make sure this solves the issue for your case

**Comment by NikolayPianikov** [comment]
Uploaded to https://plugins.jetbrains.com/plugin/11248-bazel-build-support
