### ISSUE TITLE
Non working Build Event Protocol after bazel >= 1.0.0

### ISSUE THREAD

**Issue by SKART1** [JetBrains/teamcity-bazel-plugin#3]
In bazel version >= 1.0.0

> All gRPC connections from Bazel will default to TLS enabled. To disable TLS use the grpc:// scheme in your URIs. Flags affected are: --remote_cache, --remote_executor and --bes_backend. See #8061 for details.

while bazel-event-service is passing version without explicitly set protocol and waiting plaing messages (without TLS)

We solved this problem by temporary adding proxy script which ads protocol to the build command line arguments:

```bash
/home/teamcity/.bazel/bin/bazel `echo $* | sed -e 's/--bes_backend=localhost/--bes_backend=grpc:\/\/localhost/'
```

**Comment by NikolayPianikov** [comment]
Fixed
