### ISSUE TITLE
Unsupported Bazel event types

### ISSUE THREAD

**Issue by odisseus** [JetBrains/teamcity-bazel-plugin#36]
I'm seeing this message in my build logs:
```
[2024-01-19 10:24:25,746]   INFO - SEVERE: Unknown bazel event type: id {
[2024-01-19 10:24:25,746]   INFO -   27: {
[2024-01-19 10:24:25,746]   INFO -   }
```

Apparently, there are a few [event types](https://github.com/bazelbuild/bazel/blame/b157016f62618226eee9eed7b29bb6614108229f/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto#L1333) which have been added since 2019, and the plugin doesn't know about them.

**Comment by odisseus** [comment]
How do I add support for a new event type? Beside adding a new [Protobuf definition](https://github.com/JetBrains/teamcity-bazel-plugin/blob/master/plugin-bazel-event-service/src/main/proto/build_event_stream.proto#L717), do I also need to add a new class that extends [`BazelContent`](https://github.com/JetBrains/teamcity-bazel-plugin/blob/master/plugin-bazel-event-service/src/main/kotlin/bazel/bazel/events/BazelContent.kt), a new FooHandler in [`bazel.bazel.handlers`](https://github.com/JetBrains/teamcity-bazel-plugin/tree/master/plugin-bazel-event-service/src/main/kotlin/bazel/bazel/handlers), and a new entry in [`BazelEventConverter.handlers`](https://github.com/JetBrains/teamcity-bazel-plugin/blob/master/plugin-bazel-event-service/src/main/kotlin/bazel/bazel/converters/BazelEventConverter.kt#L26)? That looks like a lot of boilerplate to me.

**Comment by vmayushan** [comment]
Hi!

As an example I have found these two commits:
https://github.com/JetBrains/teamcity-bazel-plugin/commit/05538aad6cfb29a68f6dd0b64adbdf8c41283c94
and
https://github.com/JetBrains/teamcity-bazel-plugin/commit/1e840c8f9b7a9f60c57e7dac9c7320013c927294

and indeed it looks like a lot of boilerplate
