### ISSUE TITLE
How to get Bazel installed on the build agent?

### ISSUE THREAD

**Issue by konste** [JetBrains/teamcity-bazel-plugin#4]
How shall we "bootstrap" Bazel on the build agent, so that it can be picked up by this plugin? Our build agents are dynamically created and cannot have Bazel pre-baked in the image, we need it installed as a build step. And we need it for Windows, Linux and Mac build agents. What do you recommend?

**Comment by NikolayPianikov** [comment]
@konste I would prefer using [bazel in docker](https://docs.bazel.build/versions/2.0.0/bazel-container.html) but it is not about Mac. Another option is to create your own images in Azure, AWS or in local Virtual Infrastructure with installed Bazel. Also try looking into [bazelisk](https://github.com/bazelbuild/bazelisk)

**Comment by konste** [comment]
At this time we settled for bringing Bazel binary down to the agent as part of the sources synchronization process using dedicated VCS root pointing to the repository where those binaries live.
