### ISSUE TITLE
TeamCity failed to initialize DSL plugin

### ISSUE THREAD

**Issue by AndreiOmelchenko** [JetBrains/teamcity-bazel-plugin#44]
> TeamCity failed to initialize DSL plugins.
> jetbrains/buildServer/configs/kotlin/buildSteps/BazelStep.kt
> [78:15] Expecting ';' after the last enum entry or '}' to close enum class body
> [78:16] Expecting member declaration
> ...
> 

steps to reproduce:
`git clone --recurse-submodules https://github.com/JetBrains/teamcity-bazel-plugin.git
cd teamcity-bazel-plugin
./gradlew clean build`
upload `plugin-bazel-server/build/distributions/teamcity-bazel-plugin.zip` to TeamCity
create Build configuration Bazel step

**Comment by vmayushan** [comment]
@AndreyOmelchenko Thank you for the report! 
It should be fixed now.
