### ISSUE TITLE
No agents satisfy the requirement bazel.path exists

### ISSUE THREAD

**Issue by konste** [JetBrains/teamcity-bazel-plugin#5]
I am trying to use the plugin version SNAPSHOT-201911121405. When I add Bazel build step to my TeamCity build configuration TC complains that no build agents satisfy the condition "bazel.path exists". I tried to defile and set `bazel.path` parameter on the build configuration level, but it does not resolve the problem. 
Doc says that the plugin is looking for Bazel in the PATH (and I have it in the PATH by the time Bazel step is executed) and does not mention `bazel.path` at all.
@NikolayPianikov Please advise!

**Comment by NikolayPianikov** [comment]
The new field `Path to bazel executable tool` is added in advanced options. It can be used to specify custom path to bazel tool (paths relative to the checkout directory are also supported). If this field is specified the agent bazel requirements is empty.
