### ISSUE TITLE
Dynamic "Targets" field makes it impossible to use property for Command field.

### ISSUE THREAD

**Issue by konste** [JetBrains/teamcity-bazel-plugin#6]
![Capture](https://user-images.githubusercontent.com/2653844/76007901-a4847800-5ec3-11ea-80ac-5dc223fec160.PNG)

When Command is set to `build` or `test` Targets field is visible and can be set, otherwise it is not visible and Bazel does not get targets on the command line. Unfortunately this little "fanciness" prevents possible use of TeamCity property in the Command field, because it kills the Targets field! 

Could you please simplify it so that Targets field is visible and active always?

**Comment by NikolayPianikov** [comment]
@konste Could you describe the concrete example? Is it possible to use `Command arguments:` as temporary workaround?

**Comment by konste** [comment]
We have base template which includes several Bazel steps and many build configurations derived from that template. Some of them are ready for testing and we want to run "bazel test" command for them. Some others have tests implemented, but those tests are far from passing and for those configurations we only want to run "bazel build", otherwise they would be permanently red. We were going to set the build command through TC property, but figured the plugin does not let us.

**Comment by NikolayPianikov** [comment]
For you case I should append some logic to check the `Command:` and if it contains a parameter reference I should not hide the `Targets:` field. Is it ok for you?

**Comment by konste** [comment]
The short answer is - yes, it would be ok.
Slightly longer answer - why not embrace simplicity and display `Targets:` field unconditionally? It would make life so much easier for many, starting with you.

**Comment by NikolayPianikov** [comment]
I think the user may get confused when we will show field which has no effect or may cause build to fall. But if it is uncomfortable I follow your suggestion
