### ISSUE TITLE
TC does not show tests execution stats during and after the build

### ISSUE THREAD

**Issue by konste** [JetBrains/teamcity-bazel-plugin#8]
I have a feeling that this functionality worked a few versions of Bazel ago, but does not work now. I may be mistaken though.

Now project page after the build looks like this:
![tc_project_page](https://user-images.githubusercontent.com/2653844/76694355-dd90bb00-662e-11ea-9367-92f617a5da3a.PNG)
Exit code 3 means build have passed but some tests failed. It would be really useful to see testing stats on the project page as it used to be, like 4 tests passed and 1 failed.
For clarity, we use "classic" plugin integration through BES.
Build log for reference looks like this:
![build_log](https://user-images.githubusercontent.com/2653844/76694389-66a7f200-662f-11ea-8b9b-e02222bc3a27.PNG)
Do you think it is a regression or misconfiguration?

**Comment by NikolayPianikov** [comment]
Issue fixed in the [version](https://plugins.jetbrains.com/plugin/11248-bazel-build-support/update/80912): TeamCity should not fail a build after failed tests
