### ISSUE TITLE
Tests are not passed to TeamCity with Bazel remote caching

### ISSUE THREAD

**Issue by konste** [JetBrains/teamcity-bazel-plugin#9]
The last fix made things substantially worse, by hiding test failures. When we have a build with some unit tests failed we want to see the build **failed** with the indication that it failed because of the tests, like this:
<img width="694" alt="2020-03-16 11_44_37-Project_ Prototype _ Overview — TeamCity" src="https://user-images.githubusercontent.com/2653844/76790639-754fef80-677c-11ea-88af-d01bdefece2a.png">
What we actually see is a completely green successful build:
<img width="600" alt="actual" src="https://user-images.githubusercontent.com/2653844/76790687-8c8edd00-677c-11ea-958c-e4a82c5c659d.png">
with no indication that there is anything wrong with it! This is very misleading and error-prone.  

At the very least please make the build fail if not all tests are passing, as it was before the last fix.
But ideally, we should see tests failed and passed stats, as in the picture.
And this stat should show up during the build, not only after the completion, as it happens for other build runners.

**Comment by NikolayPianikov** [comment]
Could you please attach a screenshot of the tab `Common Failure Conditions`.

Before this fix you had a state `Tests failed: X, passed: Y; build failed` but after this fix you should have `Tests failed: X, passed: Y`. Build was completed successfully because all tests were passed. It is expected behaviour:

![1](https://user-images.githubusercontent.com/11720017/76793711-980ef200-67d6-11ea-9a7d-aa57f5b27572.png)

But a build reports that it has failed tests. We had a discussion about that [there](https://youtrack.jetbrains.com/issue/TW-49018). But anyway another TeamCity build runners work the same way.

Bazel provides a tests report after a build. You could select `diagnostics` verbosity level and find original Bazel messages in the build log. So I am not sure it is possible to report tests progress in real-time. But if know about it please share this info

**Comment by konste** [comment]
<img width="483" alt="2020-03-16 12_40_31-Bazel Template Template — TeamCity" src="https://user-images.githubusercontent.com/2653844/76794027-71739b80-6783-11ea-857e-36d7914591f7.png">

The problem is - we have tests failing, but still the build shows Success as in my screenshot above. We want to see `Tests failed: X, passed: Y` and the build icon red, as in your screenshot, but instead we get `Succees` with the green checkmark.

In the following screenshot the only difference between the build #453 and #454 is the plugin updated. The test is still failing.
<img width="922" alt="repro" src="https://user-images.githubusercontent.com/2653844/76794556-78e77480-6784-11ea-8cd1-eeb83b9cf160.png">

**Comment by NikolayPianikov** [comment]
Thank you. It looks good. Could you attach a build log file with _diagnostics_ verbosity level?

**Comment by NikolayPianikov** [comment]
Which version of TeamCity and Bazel are you using?

**Comment by konste** [comment]
Diag build log attached. TeamCity Enterprise 2019.2.2 (build 71923) Bazel 2.2.0
[product_root_Linux_455.log.zip](https://github.com/JetBrains/teamcity-bazel-plugin/files/4340104/product_root_Linux_455.log.zip)

**Comment by NikolayPianikov** [comment]
Thanks. Could you attach a screenshot of _Overview_ page for this build?

**Comment by konste** [comment]
<img width="1582" alt="overview" src="https://user-images.githubusercontent.com/2653844/76795646-f318f880-6786-11ea-9b52-8a107b2f7fef.png">

**Comment by NikolayPianikov** [comment]
So you have no information about tests at all?

**Comment by konste** [comment]
Unless I open Build Log I have no way to see test failures.

**Comment by NikolayPianikov** [comment]
And what about passed tests? Do you have `Tests` tab for the build?

**Comment by konste** [comment]
No tests tab for the build.

**Comment by konste** [comment]
To answer your question `I am not sure it is possible to report tests progress in real-time. But if know about it please share this info` I tried to run the build with --build_event_text_file option and in the resulting file I see events like 
```
event {
id {
  test_result {
    label: "@lego//:test_tabsys"
    run: 1
    shard: 1
    attempt: 1
    configuration {
      id: "1b476220511947b79d025bbb49fa1fdc32ee46aed368223de5aa50720c305857"
    }
  }
}
test_result {
  test_action_output {
    name: "test.log"
    uri: "bytestream://10.176.116.122:2020/blobs/f9fee9b7c9cef38bb056d24e04d67aa7838620ce0a7d89369e29a937226027a1/1714"
  }
  test_action_output {
    name: "test.xml"
    uri: "bytestream://10.176.116.122:2020/blobs/143c15e5d2188abdf0962f9b851a7971d59c589fa7835a0bff77800b288257d5/2151"
  }
  test_attempt_duration_millis: 10840
  status: FAILED
  test_attempt_start_millis_epoch: 1584389752518
  execution_info {
    strategy: "processwrapper-sandbox"
  }
}
}
```
which come in as tests are passing or failing, while the build is still going, so it is possible to have that info in real time.

**Comment by NikolayPianikov** [comment]
Are you using Bazel Remote caching?
I found a difference between my and your test reports but I'm going to continue investigation tomorrow.

**Comment by konste** [comment]
Thank you, Nikolay!
We started using remote caching last week. I will try without it and report.

**Comment by konste** [comment]
Indeed it seems to be remote caching which makes the difference! When I turned remote caching off everything test related started to behave as it should. Here is diagnostic log without remote caching: 
[product_root_Linux_457.log.zip](https://github.com/JetBrains/teamcity-bazel-plugin/files/4340336/product_root_Linux_457.log.zip)
Diag log WITH remote caching is attached above (build #455).
I hope you can compare those and figure how remote caching disrupts your plugin functionality.

**Comment by NikolayPianikov** [comment]
@konste please try https://plugins.jetbrains.com/plugin/11248-bazel-build-support/update/80972

**Comment by NikolayPianikov** [comment]
I've added #10 task
